cmake_minimum_required(VERSION 3.25)

set(CMAKE_C_COMPILER "cl")
set(CMAKE_CXX_COMPILER "cl")

set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_POLICY_DEFAULT_CMP0141 "NEW")
set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "ProgramDatabase")
set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF")
set(CMAKE_SHARED_LINKER_FLAGS "/INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF")
set(CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")

set(CMAKE_CONFIGURATION_TYPES "Release")
set(CMAKE_BUILD_TYPE "Release")
